"""agregar tabla reacciones

Revision ID: 222ae4e75235
Revises: 
Create Date: 2026-09-02 08:21:45.226193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '222ae4e75235'
down_revision = 'f1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reacciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incidente_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.CheckConstraint("tipo IN ('me_afecta', 'es_urgente', 'ya_mejoro', 'sigue_igual')", name='ck_reaccion_tipo'),
    sa.ForeignKeyConstraint(['incidente_id'], ['incidentes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incidente_id', 'usuario_id', name='uq_reaccion_usuario_incidente')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reacciones')
    # ### end Alembic commands ###
