"""agregar tabla tokens_revocados

Revision ID: c97f00b92f7a
Revises: 222ae4e75235
Create Date: 2026-09-21 20:17:54.103173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c97f00b92f7a'
down_revision = '222ae4e75235'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens_revocados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('fecha_revocacion', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tokens_revocados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tokens_revocados_jti'), ['jti'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens_revocados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tokens_revocados_jti'))

    op.drop_table('tokens_revocados')
    # ### end Alembic commands ###
